/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/keyboard.glb 
Author: BlackCube (https://sketchfab.com/blackcube4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/logitech-mechanical-gaming-keyboard-c775d45baf854606931584404d7b9109
Title: Logitech mechanical gaming keyboard
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Keyboard(props) {
    const { nodes, materials } = useGLTF('./models/keyboard.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh geometry={nodes.Tastatur_Tastatur_Seite_0.geometry} material={materials.Tastatur_Seite} />
                <mesh geometry={nodes.Tastatur_Tastatur_Untergrund_0.geometry} material={materials.Tastatur_Untergrund} />
                <mesh geometry={nodes.Tastatur_Tastatur_Unterseite_0.geometry} material={materials.Tastatur_Unterseite} />
                <mesh geometry={nodes['Tastatur_Tastatur_F����chen_0'].geometry} material={materials.Tastatur_Fchen} />
            </group>
            <group rotation={[-1.481, 0, 0]} scale={100}>
                <mesh geometry={nodes.Tasten_Kappen_Tasten_0.geometry} material={materials.Tasten} />
                <mesh geometry={nodes.Tasten_Kappen_Tasten_Emission_0.geometry} material={materials.Tasten_Emission} />
            </group>
            <mesh geometry={nodes.Tasten_Tasten_2_0.geometry} material={materials.Tasten_2} rotation={[-1.481, 0, 0]} scale={100} />
        </group>
    )
}

useGLTF.preload('./models/keyboard.glb')
